# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\VgarciaChallenge\Shared\Application\Command\CommandHandler:
            tags: ['app.command_handler']
        App\VgarciaChallenge\Shared\Application\Query\QueryHandler:
            tags: ['app.query_handler']
        App\VgarciaChallenge\Shared\Domain\Event\DomainEventSubscriber:
            tags: ['app.domain_event_subscriber']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/**/tests'
            - '../src/**/Infrastructure/Persistence/Doctrine/Mapping'

    App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncCommandBus:
        arguments:
            $handlers: !tagged_iterator app.command_handler

    App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncQueryBus:
        arguments:
            $handlers: !tagged_iterator app.query_handler

    App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncDomainEventBus:
        arguments:
            $subscribers: !tagged_iterator app.domain_event_subscriber

    App\VgarciaChallenge\Shared\Application\Command\CommandBus:
        alias: App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncCommandBus

    App\VgarciaChallenge\Shared\Application\Query\QueryBus:
        alias: App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncQueryBus

    App\VgarciaChallenge\Shared\Domain\Event\DomainEventBus:
        alias: App\VgarciaChallenge\Shared\Infrastructure\Bus\SyncDomainEventBus

    App\VgarciaChallenge\Vending\Domain\VendingMachine\VendingMachineRepository:
        alias: App\VgarciaChallenge\Vending\Infrastructure\Persistence\Doctrine\Repository\DoctrineVendingMachineRepository

    App\VgarciaChallenge\Vending\Domain\Order\OrderRepository:
        alias: App\VgarciaChallenge\Vending\Infrastructure\Persistence\Doctrine\Repository\DoctrineOrderRepository

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
