name: Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: ctype, iconv, dom, mbstring, xml, xmlwriter, xmlreader, intl, zip

      - name: Validate Composer files
        run: composer validate --no-check-publish

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --no-scripts

      - name: Regenerate autoload
        run: composer dump-autoload

      - name: Run test suite
        run: php vendor/bin/phpunit --colors=always
